spring:
  config:
    activate:
      on-profile: default
  cloud:
    stream:
      functions: receiveMessage-in-0
      bindings:
        publishMessage-out-0:
          content-type: application/json
          destination: testing.exchange
          group: spring.to.dashboard
        receiveMessage-in-0:
          content-type: application/json
          destination: testing.exchange
          group: dashboard.to.spring
      rabbit:
        bindings:
          publishMessage-out-0:
            producer:
              bindQueue: true
              bindingRoutingKey: spring.to.dashboard
              routingKey: spring.to.spring
              routing-key-expression: '"spring.to.spring"'
          receiveMessage-in-0:
            consumer:
              bindQueue: true
              declareExchange: true
              queueNameGroupOnly: true




